/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientlourdredfox.ConnexionAccueil;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author jeoffrey
 */
public class Accueil extends javax.swing.JFrame {

    private JPanel currentPanel = null;

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGestionDesjeux = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListJeu = new javax.swing.JList();
        jPanelAjoutJeu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomJeu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescrptionJeu = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButtonAjouterJeu = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jPanelSuppresionJeu = new javax.swing.JPanel();
        jButtonSupprimerJeu = new javax.swing.JButton();
        jPanelModificationJeux = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldModifierNomJeux = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaDescrptionJeu1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButtonModifierJeu = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jPanelGestionJoueur = new javax.swing.JPanel();
        jPanelGestionAdherent = new javax.swing.JPanel();
        jPanelGestionAdministrateurs = new javax.swing.JPanel();
        jPanelGestionUtilisateur = new javax.swing.JPanel();
        jPanelGestionResultat = new javax.swing.JPanel();
        jPanelGestionDesEquipes = new javax.swing.JPanel();
        jPanelGestionAdhesions = new javax.swing.JPanel();
        jPanelGestionMatch = new javax.swing.JPanel();
        jPanelPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAccueil = new javax.swing.JMenu();
        jMenuGestionUnilan = new javax.swing.JMenu();
        jMenuGestionDesUtilisateurs = new javax.swing.JMenu();
        jMenuItemAdherent = new javax.swing.JMenuItem();
        jMenuItemUtilisateurs = new javax.swing.JMenuItem();
        jMenuItemGestionJoueurs = new javax.swing.JMenuItem();
        jMenuItemGestionDesJeux = new javax.swing.JMenuItem();
        jMenuItemGestionAdmin = new javax.swing.JMenuItem();
        jMenuItemGestionAdhesion = new javax.swing.JMenuItem();
        jMenuGestionRedfox = new javax.swing.JMenu();
        jMenuItemMatch = new javax.swing.JMenuItem();
        jMenuItemGestionEquipe = new javax.swing.JMenuItem();
        jMenuItemGestionRésultats = new javax.swing.JMenuItem();
        jMenuAlarmes = new javax.swing.JMenu();
        jMenuAide = new javax.swing.JMenu();

        jPanelGestionDesjeux.setBackground(new java.awt.Color(102, 102, 102));

        jListJeu.setBackground(new java.awt.Color(102, 102, 102));
        jListJeu.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListJeu);

        jPanelAjoutJeu.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajout d'un jeu"));

        jLabel1.setText("Nom :");

        jLabel2.setText("Description :");

        jTextAreaDescrptionJeu.setColumns(20);
        jTextAreaDescrptionJeu.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDescrptionJeu);

        jLabel3.setText("Image :");

        jButtonAjouterJeu.setText("Ajouter");

        jTextField2.setText("Système d'ajout de document");

        javax.swing.GroupLayout jPanelAjoutJeuLayout = new javax.swing.GroupLayout(jPanelAjoutJeu);
        jPanelAjoutJeu.setLayout(jPanelAjoutJeuLayout);
        jPanelAjoutJeuLayout.setHorizontalGroup(
            jPanelAjoutJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAjoutJeuLayout.createSequentialGroup()
                .addGroup(jPanelAjoutJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanelAjoutJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAjouterJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanelAjoutJeuLayout.setVerticalGroup(
            jPanelAjoutJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAjoutJeuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAjoutJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNomJeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAjoutJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAjoutJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButtonAjouterJeu))
        );

        jPanelSuppresionJeu.setBorder(javax.swing.BorderFactory.createTitledBorder("Suppression d'un jeu"));

        jButtonSupprimerJeu.setText("Supprimer");

        javax.swing.GroupLayout jPanelSuppresionJeuLayout = new javax.swing.GroupLayout(jPanelSuppresionJeu);
        jPanelSuppresionJeu.setLayout(jPanelSuppresionJeuLayout);
        jPanelSuppresionJeuLayout.setHorizontalGroup(
            jPanelSuppresionJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSuppresionJeuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSupprimerJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
        );
        jPanelSuppresionJeuLayout.setVerticalGroup(
            jPanelSuppresionJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuppresionJeuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSupprimerJeu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelModificationJeux.setBorder(javax.swing.BorderFactory.createTitledBorder("Modifier un jeu"));

        jLabel4.setText("Nom :");

        jLabel5.setText("Description :");

        jTextAreaDescrptionJeu1.setColumns(20);
        jTextAreaDescrptionJeu1.setRows(5);
        jScrollPane3.setViewportView(jTextAreaDescrptionJeu1);

        jLabel6.setText("Image :");

        jButtonModifierJeu.setText("Modifier");

        jTextField3.setText("Système d'ajout de document");

        javax.swing.GroupLayout jPanelModificationJeuxLayout = new javax.swing.GroupLayout(jPanelModificationJeux);
        jPanelModificationJeux.setLayout(jPanelModificationJeuxLayout);
        jPanelModificationJeuxLayout.setHorizontalGroup(
            jPanelModificationJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModificationJeuxLayout.createSequentialGroup()
                .addGroup(jPanelModificationJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanelModificationJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModifierJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldModifierNomJeux, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelModificationJeuxLayout.setVerticalGroup(
            jPanelModificationJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModificationJeuxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModificationJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldModifierNomJeux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelModificationJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModificationJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButtonModifierJeu))
        );

        javax.swing.GroupLayout jPanelGestionDesjeuxLayout = new javax.swing.GroupLayout(jPanelGestionDesjeux);
        jPanelGestionDesjeux.setLayout(jPanelGestionDesjeuxLayout);
        jPanelGestionDesjeuxLayout.setHorizontalGroup(
            jPanelGestionDesjeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionDesjeuxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelGestionDesjeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAjoutJeu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelModificationJeux, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelGestionDesjeuxLayout.createSequentialGroup()
                        .addComponent(jPanelSuppresionJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(88, 88, 88))
        );
        jPanelGestionDesjeuxLayout.setVerticalGroup(
            jPanelGestionDesjeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionDesjeuxLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelGestionDesjeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGestionDesjeuxLayout.createSequentialGroup()
                        .addComponent(jPanelModificationJeux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jPanelSuppresionJeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jPanelAjoutJeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 197, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jPanelGestionJoueur.setBackground(new java.awt.Color(51, 255, 153));

        javax.swing.GroupLayout jPanelGestionJoueurLayout = new javax.swing.GroupLayout(jPanelGestionJoueur);
        jPanelGestionJoueur.setLayout(jPanelGestionJoueurLayout);
        jPanelGestionJoueurLayout.setHorizontalGroup(
            jPanelGestionJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
        );
        jPanelGestionJoueurLayout.setVerticalGroup(
            jPanelGestionJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        jPanelGestionAdherent.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanelGestionAdherentLayout = new javax.swing.GroupLayout(jPanelGestionAdherent);
        jPanelGestionAdherent.setLayout(jPanelGestionAdherentLayout);
        jPanelGestionAdherentLayout.setHorizontalGroup(
            jPanelGestionAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );
        jPanelGestionAdherentLayout.setVerticalGroup(
            jPanelGestionAdherentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        jPanelGestionAdministrateurs.setBackground(new java.awt.Color(153, 255, 102));

        javax.swing.GroupLayout jPanelGestionAdministrateursLayout = new javax.swing.GroupLayout(jPanelGestionAdministrateurs);
        jPanelGestionAdministrateurs.setLayout(jPanelGestionAdministrateursLayout);
        jPanelGestionAdministrateursLayout.setHorizontalGroup(
            jPanelGestionAdministrateursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        jPanelGestionAdministrateursLayout.setVerticalGroup(
            jPanelGestionAdministrateursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        jPanelGestionUtilisateur.setBackground(new java.awt.Color(102, 51, 0));

        javax.swing.GroupLayout jPanelGestionUtilisateurLayout = new javax.swing.GroupLayout(jPanelGestionUtilisateur);
        jPanelGestionUtilisateur.setLayout(jPanelGestionUtilisateurLayout);
        jPanelGestionUtilisateurLayout.setHorizontalGroup(
            jPanelGestionUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        jPanelGestionUtilisateurLayout.setVerticalGroup(
            jPanelGestionUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        jPanelGestionResultat.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout jPanelGestionResultatLayout = new javax.swing.GroupLayout(jPanelGestionResultat);
        jPanelGestionResultat.setLayout(jPanelGestionResultatLayout);
        jPanelGestionResultatLayout.setHorizontalGroup(
            jPanelGestionResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        jPanelGestionResultatLayout.setVerticalGroup(
            jPanelGestionResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelGestionDesEquipesLayout = new javax.swing.GroupLayout(jPanelGestionDesEquipes);
        jPanelGestionDesEquipes.setLayout(jPanelGestionDesEquipesLayout);
        jPanelGestionDesEquipesLayout.setHorizontalGroup(
            jPanelGestionDesEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        jPanelGestionDesEquipesLayout.setVerticalGroup(
            jPanelGestionDesEquipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        jPanelGestionAdhesions.setBackground(new java.awt.Color(51, 51, 51));
        jPanelGestionAdhesions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));

        javax.swing.GroupLayout jPanelGestionAdhesionsLayout = new javax.swing.GroupLayout(jPanelGestionAdhesions);
        jPanelGestionAdhesions.setLayout(jPanelGestionAdhesionsLayout);
        jPanelGestionAdhesionsLayout.setHorizontalGroup(
            jPanelGestionAdhesionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        jPanelGestionAdhesionsLayout.setVerticalGroup(
            jPanelGestionAdhesionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        jPanelGestionMatch.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanelGestionMatchLayout = new javax.swing.GroupLayout(jPanelGestionMatch);
        jPanelGestionMatch.setLayout(jPanelGestionMatchLayout);
        jPanelGestionMatchLayout.setHorizontalGroup(
            jPanelGestionMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        jPanelGestionMatchLayout.setVerticalGroup(
            jPanelGestionMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPrincipal.setBackground(new java.awt.Color(153, 153, 153));
        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 51, 51), 2));
        jPanelPrincipal.setLayout(new java.awt.BorderLayout());

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));

        jMenuAccueil.setText("Accueil");
        jMenuAccueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAccueilMouseClicked(evt);
            }
        });
        jMenuAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourAccueil(evt);
            }
        });
        jMenuBar1.add(jMenuAccueil);

        jMenuGestionUnilan.setText("Gestion de Unilan");

        jMenuGestionDesUtilisateurs.setText("Gestion des Utilisateurs");

        jMenuItemAdherent.setText("Adhérents");
        jMenuItemAdherent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdherentActionPerformed(evt);
            }
        });
        jMenuGestionDesUtilisateurs.add(jMenuItemAdherent);

        jMenuItemUtilisateurs.setText("Utilisateurs");
        jMenuItemUtilisateurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUtilisateursActionPerformed(evt);
            }
        });
        jMenuGestionDesUtilisateurs.add(jMenuItemUtilisateurs);

        jMenuItemGestionJoueurs.setText("Joueurs");
        jMenuItemGestionJoueurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionJoueursActionPerformed(evt);
            }
        });
        jMenuGestionDesUtilisateurs.add(jMenuItemGestionJoueurs);

        jMenuGestionUnilan.add(jMenuGestionDesUtilisateurs);

        jMenuItemGestionDesJeux.setText("Gestion des Jeux");
        jMenuItemGestionDesJeux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionDesJeuxActionPerformed(evt);
            }
        });
        jMenuGestionUnilan.add(jMenuItemGestionDesJeux);

        jMenuItemGestionAdmin.setText("Gestion des Administrateurs");
        jMenuItemGestionAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionAdminActionPerformed(evt);
            }
        });
        jMenuGestionUnilan.add(jMenuItemGestionAdmin);

        jMenuItemGestionAdhesion.setText("Gestion des Adhésions");
        jMenuItemGestionAdhesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionAdhesionActionPerformed(evt);
            }
        });
        jMenuGestionUnilan.add(jMenuItemGestionAdhesion);

        jMenuBar1.add(jMenuGestionUnilan);

        jMenuGestionRedfox.setText("Gestion de Redfox");

        jMenuItemMatch.setText("Gestion des Matchs");
        jMenuItemMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMatchActionPerformed(evt);
            }
        });
        jMenuGestionRedfox.add(jMenuItemMatch);

        jMenuItemGestionEquipe.setText("Gestion des Equipes");
        jMenuItemGestionEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionEquipeActionPerformed(evt);
            }
        });
        jMenuGestionRedfox.add(jMenuItemGestionEquipe);

        jMenuItemGestionRésultats.setText("Gestion des Résultats");
        jMenuItemGestionRésultats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionRésultatsActionPerformed(evt);
            }
        });
        jMenuGestionRedfox.add(jMenuItemGestionRésultats);

        jMenuBar1.add(jMenuGestionRedfox);

        jMenuAlarmes.setText("Notifications");
        jMenuAlarmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickAlarme(evt);
            }
        });
        jMenuBar1.add(jMenuAlarmes);

        jMenuAide.setText("Aide");
        jMenuAide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAideMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuAide);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGestionAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionAdminActionPerformed

        if(currentPanel != null)
        jPanelPrincipal.remove(currentPanel);
        
        currentPanel = this.jPanelGestionAdministrateurs;
        jPanelPrincipal.add(currentPanel, BorderLayout.CENTER);
        jPanelPrincipal.invalidate();

    }//GEN-LAST:event_jMenuItemGestionAdminActionPerformed

    private void jMenuItemGestionDesJeuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionDesJeuxActionPerformed

        if(currentPanel != null)
        jPanelPrincipal.remove(currentPanel);
        
        currentPanel = this.jPanelGestionDesjeux;
        jPanelPrincipal.add(currentPanel, BorderLayout.CENTER);
        jPanelPrincipal.invalidate();

    }//GEN-LAST:event_jMenuItemGestionDesJeuxActionPerformed

    private void RetourAccueil(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourAccueil
        
        if(currentPanel != null)
        jPanelPrincipal.remove(currentPanel);
        
        currentPanel = this.jPanelPrincipal;
        jPanelPrincipal.add(currentPanel, BorderLayout.CENTER);
        jPanelPrincipal.invalidate();
        
        
    }//GEN-LAST:event_RetourAccueil

    private void jMenuItemGestionAdhesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionAdhesionActionPerformed
       if(currentPanel != null)
        jPanelPrincipal.remove(currentPanel);
        
        currentPanel = this.jPanelGestionAdhesions;
        jPanelPrincipal.add(currentPanel, BorderLayout.CENTER);
        jPanelPrincipal.invalidate();
    }//GEN-LAST:event_jMenuItemGestionAdhesionActionPerformed

    private void jMenuItemMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMatchActionPerformed
     
        if(currentPanel != null)
        jPanelPrincipal.remove(currentPanel);
        
        currentPanel = this.jPanelGestionMatch;
        jPanelPrincipal.add(currentPanel, BorderLayout.CENTER);
        jPanelPrincipal.invalidate();
        
    }//GEN-LAST:event_jMenuItemMatchActionPerformed

    private void jMenuItemGestionEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionEquipeActionPerformed
        if(currentPanel != null)
        jPanelPrincipal.remove(currentPanel);
        
        currentPanel = this.jPanelGestionDesEquipes;
        jPanelPrincipal.add(currentPanel, BorderLayout.CENTER);
        jPanelPrincipal.invalidate();
    }//GEN-LAST:event_jMenuItemGestionEquipeActionPerformed

    private void jMenuItemAdherentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdherentActionPerformed
        if(currentPanel != null)
        jPanelPrincipal.remove(currentPanel);
        
        currentPanel = this.jPanelGestionAdherent;
        jPanelPrincipal.add(currentPanel, BorderLayout.CENTER);
        jPanelPrincipal.invalidate();
    }//GEN-LAST:event_jMenuItemAdherentActionPerformed

    private void jMenuItemUtilisateursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUtilisateursActionPerformed
        if(currentPanel != null)
        jPanelPrincipal.remove(currentPanel);
        
        currentPanel = this.jPanelGestionUtilisateur;
        jPanelPrincipal.add(currentPanel, BorderLayout.CENTER);
        jPanelPrincipal.invalidate();
    }//GEN-LAST:event_jMenuItemUtilisateursActionPerformed

    private void jMenuItemGestionJoueursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionJoueursActionPerformed
         if(currentPanel != null)
        jPanelPrincipal.remove(currentPanel);
        
        currentPanel = this.jPanelGestionJoueur;
        jPanelPrincipal.add(currentPanel, BorderLayout.CENTER);
        jPanelPrincipal.invalidate();
                                       
    }//GEN-LAST:event_jMenuItemGestionJoueursActionPerformed

    private void jMenuItemGestionRésultatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionRésultatsActionPerformed
        if(currentPanel != null)
        jPanelPrincipal.remove(currentPanel);
        
        currentPanel = this.jPanelGestionResultat;
        jPanelPrincipal.add(currentPanel, BorderLayout.CENTER);
        jPanelPrincipal.invalidate();
    }//GEN-LAST:event_jMenuItemGestionRésultatsActionPerformed

    private void jMenuAccueilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAccueilMouseClicked
        if(currentPanel != null)
        jPanelPrincipal.remove(currentPanel);
        
        
        currentPanel = this.jPanelPrincipal;
        jPanelPrincipal.add(currentPanel, BorderLayout.CENTER);
        jPanelPrincipal.invalidate();
        
    }//GEN-LAST:event_jMenuAccueilMouseClicked

    private void jMenuAideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAideMouseClicked
        Aide.Aide aide = new Aide.Aide();
        aide.show();
    }//GEN-LAST:event_jMenuAideMouseClicked

    private void MouseClickAlarme(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickAlarme
        notifications.Notifications notif = new notifications.Notifications();
        notif.show();
    }//GEN-LAST:event_MouseClickAlarme

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouterJeu;
    private javax.swing.JButton jButtonModifierJeu;
    private javax.swing.JButton jButtonSupprimerJeu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jListJeu;
    private javax.swing.JMenu jMenuAccueil;
    private javax.swing.JMenu jMenuAide;
    private javax.swing.JMenu jMenuAlarmes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGestionDesUtilisateurs;
    private javax.swing.JMenu jMenuGestionRedfox;
    private javax.swing.JMenu jMenuGestionUnilan;
    private javax.swing.JMenuItem jMenuItemAdherent;
    private javax.swing.JMenuItem jMenuItemGestionAdhesion;
    private javax.swing.JMenuItem jMenuItemGestionAdmin;
    private javax.swing.JMenuItem jMenuItemGestionDesJeux;
    private javax.swing.JMenuItem jMenuItemGestionEquipe;
    private javax.swing.JMenuItem jMenuItemGestionJoueurs;
    private javax.swing.JMenuItem jMenuItemGestionRésultats;
    private javax.swing.JMenuItem jMenuItemMatch;
    private javax.swing.JMenuItem jMenuItemUtilisateurs;
    private javax.swing.JPanel jPanelAjoutJeu;
    private javax.swing.JPanel jPanelGestionAdherent;
    private javax.swing.JPanel jPanelGestionAdhesions;
    private javax.swing.JPanel jPanelGestionAdministrateurs;
    private javax.swing.JPanel jPanelGestionDesEquipes;
    private javax.swing.JPanel jPanelGestionDesjeux;
    private javax.swing.JPanel jPanelGestionJoueur;
    private javax.swing.JPanel jPanelGestionMatch;
    private javax.swing.JPanel jPanelGestionResultat;
    private javax.swing.JPanel jPanelGestionUtilisateur;
    private javax.swing.JPanel jPanelModificationJeux;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelSuppresionJeu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaDescrptionJeu;
    private javax.swing.JTextArea jTextAreaDescrptionJeu1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldModifierNomJeux;
    private javax.swing.JTextField jTextFieldNomJeu;
    // End of variables declaration//GEN-END:variables
}
