/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aide;

/**
 *
 * @author jeoffrey
 */
public class Aide extends javax.swing.JFrame {

    /**
     * Creates new form Aide
     */
    public Aide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAccueilAide = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAccueil = new javax.swing.JMenu();
        jMenuGestionUnilan = new javax.swing.JMenu();
        jMenuAideUtilisateurs = new javax.swing.JMenuItem();
        jMenuItemGestionDesJeux = new javax.swing.JMenuItem();
        jMenuItemGestionAdmin = new javax.swing.JMenuItem();
        jMenuItemGestionAdhesion = new javax.swing.JMenuItem();
        jMenuGestionRedfox = new javax.swing.JMenu();
        jMenuItemMatch = new javax.swing.JMenuItem();
        jMenuItemGestionEquipe = new javax.swing.JMenuItem();
        jMenuItemGestionRésultats = new javax.swing.JMenuItem();
        jMenuAlarmes = new javax.swing.JMenu();
        jMenuAide = new javax.swing.JMenu();

        setTitle("Aide");

        javax.swing.GroupLayout jPanelAccueilAideLayout = new javax.swing.GroupLayout(jPanelAccueilAide);
        jPanelAccueilAide.setLayout(jPanelAccueilAideLayout);
        jPanelAccueilAideLayout.setHorizontalGroup(
            jPanelAccueilAideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        jPanelAccueilAideLayout.setVerticalGroup(
            jPanelAccueilAideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));

        jMenuAccueil.setText("Accueil");
        jMenuAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAccueilRetourAccueil(evt);
            }
        });
        jMenuBar1.add(jMenuAccueil);

        jMenuGestionUnilan.setText("Gestion de Unilan");
        jMenuGestionUnilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGestionUnilanActionPerformed(evt);
            }
        });

        jMenuAideUtilisateurs.setText("Utilisateur");
        jMenuGestionUnilan.add(jMenuAideUtilisateurs);

        jMenuItemGestionDesJeux.setText("Gestion des Jeux");
        jMenuItemGestionDesJeux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemGestionDesJeuxMouseClicked(evt);
            }
        });
        jMenuItemGestionDesJeux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionDesJeuxActionPerformed(evt);
            }
        });
        jMenuGestionUnilan.add(jMenuItemGestionDesJeux);

        jMenuItemGestionAdmin.setText("Gestion des Administrateurs");
        jMenuItemGestionAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionAdminActionPerformed(evt);
            }
        });
        jMenuGestionUnilan.add(jMenuItemGestionAdmin);

        jMenuItemGestionAdhesion.setText("Gestion des Adhésions");
        jMenuItemGestionAdhesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionAdhesionActionPerformed(evt);
            }
        });
        jMenuGestionUnilan.add(jMenuItemGestionAdhesion);

        jMenuBar1.add(jMenuGestionUnilan);

        jMenuGestionRedfox.setText("Gestion de Redfox");

        jMenuItemMatch.setText("Gestion des Matchs");
        jMenuItemMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMatchActionPerformed(evt);
            }
        });
        jMenuGestionRedfox.add(jMenuItemMatch);

        jMenuItemGestionEquipe.setText("Gestion des Equipes");
        jMenuItemGestionEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionEquipeActionPerformed(evt);
            }
        });
        jMenuGestionRedfox.add(jMenuItemGestionEquipe);

        jMenuItemGestionRésultats.setText("Gestion des Résultats");
        jMenuItemGestionRésultats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionRésultatsActionPerformed(evt);
            }
        });
        jMenuGestionRedfox.add(jMenuItemGestionRésultats);

        jMenuBar1.add(jMenuGestionRedfox);

        jMenuAlarmes.setText("Notifications");
        jMenuBar1.add(jMenuAlarmes);

        jMenuAide.setText("Aide");
        jMenuBar1.add(jMenuAide);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelAccueilAide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelAccueilAide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAccueilRetourAccueil(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAccueilRetourAccueil

      

    }//GEN-LAST:event_jMenuAccueilRetourAccueil

    private void jMenuItemGestionDesJeuxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemGestionDesJeuxMouseClicked

    }//GEN-LAST:event_jMenuItemGestionDesJeuxMouseClicked

    private void jMenuItemGestionDesJeuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionDesJeuxActionPerformed

     
    }//GEN-LAST:event_jMenuItemGestionDesJeuxActionPerformed

    private void jMenuItemGestionAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionAdminActionPerformed

       
    }//GEN-LAST:event_jMenuItemGestionAdminActionPerformed

    private void jMenuItemGestionAdhesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionAdhesionActionPerformed
       
    }//GEN-LAST:event_jMenuItemGestionAdhesionActionPerformed

    private void jMenuGestionUnilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGestionUnilanActionPerformed

    }//GEN-LAST:event_jMenuGestionUnilanActionPerformed

    private void jMenuItemMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMatchActionPerformed

        
    }//GEN-LAST:event_jMenuItemMatchActionPerformed

    private void jMenuItemGestionEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionEquipeActionPerformed
    
    }//GEN-LAST:event_jMenuItemGestionEquipeActionPerformed

    private void jMenuItemGestionRésultatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionRésultatsActionPerformed
        
    }//GEN-LAST:event_jMenuItemGestionRésultatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAccueil;
    private javax.swing.JMenu jMenuAide;
    private javax.swing.JMenuItem jMenuAideUtilisateurs;
    private javax.swing.JMenu jMenuAlarmes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGestionRedfox;
    private javax.swing.JMenu jMenuGestionUnilan;
    private javax.swing.JMenuItem jMenuItemGestionAdhesion;
    private javax.swing.JMenuItem jMenuItemGestionAdmin;
    private javax.swing.JMenuItem jMenuItemGestionDesJeux;
    private javax.swing.JMenuItem jMenuItemGestionEquipe;
    private javax.swing.JMenuItem jMenuItemGestionRésultats;
    private javax.swing.JMenuItem jMenuItemMatch;
    private javax.swing.JPanel jPanelAccueilAide;
    // End of variables declaration//GEN-END:variables
}
