/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aide;

/**
 *
 * @author jeoffrey
 */
public class Aide extends javax.swing.JFrame {

    /**
     * Creates new form Aide
     */
    public Aide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAccueilAide = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelDescriptionAide = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelGesionUnilan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButtonAideGestionUtilisateur = new javax.swing.JButton();
        jButtonAideGestionAdmin = new javax.swing.JButton();
        jButtonAideGestionJeux = new javax.swing.JButton();
        jButtonAideAdhésions = new javax.swing.JButton();
        jPanelGestionRedfox = new javax.swing.JPanel();
        jPanelGestionNotifications = new javax.swing.JPanel();
        jPanelAideGestionUtilisateur = new javax.swing.JPanel();
        jPanelAideGestionJeux = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAccueil = new javax.swing.JMenu();
        jMenuGestionUnilan = new javax.swing.JMenu();
        jMenuGestionRedfox = new javax.swing.JMenu();
        jMenuAlarmes = new javax.swing.JMenu();

        setTitle("Aide");
        setMaximumSize(new java.awt.Dimension(2114444, 2114444));
        setMinimumSize(null);

        jPanelAccueilAide.setBackground(new java.awt.Color(102, 102, 102));

        jPanelDescriptionAide.setBackground(new java.awt.Color(153, 153, 153));
        jPanelDescriptionAide.setBorder(javax.swing.BorderFactory.createTitledBorder("Fenêtre d'aide a l'utilisation"));

        jLabel1.setText("Bienvenue sur la fenêtre d'aide du logiciel :");

        jLabel2.setText("- Vous trouverez ici des explications relatifs à chacune des fonctions présentes sur le logiciel ");

        jLabel3.setText("Vous avez la possibilité a tout moment de revenir sur l'application en rebasculant la fenêtre.");

        jLabel4.setText("- Pour trouver l'explication relative à votre interrogation sélectionner dans le menu la gestion associé");

        javax.swing.GroupLayout jPanelDescriptionAideLayout = new javax.swing.GroupLayout(jPanelDescriptionAide);
        jPanelDescriptionAide.setLayout(jPanelDescriptionAideLayout);
        jPanelDescriptionAideLayout.setHorizontalGroup(
            jPanelDescriptionAideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescriptionAideLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanelDescriptionAideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDescriptionAideLayout.setVerticalGroup(
            jPanelDescriptionAideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescriptionAideLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanelDescriptionAide);

        jPanelGesionUnilan.setBackground(new java.awt.Color(102, 102, 102));
        jPanelGesionUnilan.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion de Unilan "));

        jLabel5.setText("L'onglet gestion de Unilan permet via plusieurs sous-menu de gérer certaines données liées a la base de donnée :");

        jLabel6.setText("- La gestion des utilisateurs ( Adhérents , Joueurs et Utilisateurs).");

        jLabel7.setText("- La gestion des Jeux ");

        jLabel8.setText("Permet l'ajout, la suppression et la modification des différentes informations relatives à ces utilisateurs.");

        jLabel9.setText("Donne la possibilité d'ajouter de nouveaux jeux d'en supprimer mais aussi de modifier des jeux existants.");

        jLabel10.setText("- Gestion des administrateurs ");

        jLabel11.setText("Permet la gestion des statuts administrateurs en donnant la possibilités de les modifier d'en rajouter ou bien même de les supprimer.");

        jLabel12.setText("- Gestion des adhésions");

        jLabel13.setText("Utilisé pour la gestion des différents adhérents via un panel comprennant la midification, l'ajout ainsi que la suppression.");
        jLabel13.setToolTipText("");

        jButtonAideGestionUtilisateur.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAideGestionUtilisateur.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonAideGestionUtilisateur.setText("Gestion utilisateur");

        jButtonAideGestionAdmin.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAideGestionAdmin.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonAideGestionAdmin.setText("Gestion des Administrateurs");

        jButtonAideGestionJeux.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAideGestionJeux.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonAideGestionJeux.setText("Gestion des Jeux");

        jButtonAideAdhésions.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAideAdhésions.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonAideAdhésions.setText("Gestion des Adhésions");

        javax.swing.GroupLayout jPanelGesionUnilanLayout = new javax.swing.GroupLayout(jPanelGesionUnilan);
        jPanelGesionUnilan.setLayout(jPanelGesionUnilanLayout);
        jPanelGesionUnilanLayout.setHorizontalGroup(
            jPanelGesionUnilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGesionUnilanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGesionUnilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGesionUnilanLayout.createSequentialGroup()
                        .addGroup(jPanelGesionUnilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13)
                            .addGroup(jPanelGesionUnilanLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(323, 323, 323)
                                .addComponent(jButtonAideGestionAdmin))
                            .addComponent(jLabel9)
                            .addGroup(jPanelGesionUnilanLayout.createSequentialGroup()
                                .addGroup(jPanelGesionUnilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(195, 195, 195)
                                .addGroup(jPanelGesionUnilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAideGestionUtilisateur)
                                    .addComponent(jButtonAideGestionJeux)))
                            .addComponent(jLabel8))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelGesionUnilanLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAideAdhésions)
                        .addGap(23, 23, 23))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGesionUnilanLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        jPanelGesionUnilanLayout.setVerticalGroup(
            jPanelGesionUnilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGesionUnilanLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addGap(39, 39, 39)
                .addGroup(jPanelGesionUnilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButtonAideGestionUtilisateur))
                .addGap(9, 9, 9)
                .addComponent(jLabel8)
                .addGap(40, 40, 40)
                .addGroup(jPanelGesionUnilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButtonAideGestionJeux))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(48, 48, 48)
                .addGroup(jPanelGesionUnilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jButtonAideGestionAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(49, 49, 49)
                .addGroup(jPanelGesionUnilanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jButtonAideAdhésions))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanelGesionUnilan);

        jPanelGestionRedfox.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion de Redfox"));

        javax.swing.GroupLayout jPanelGestionRedfoxLayout = new javax.swing.GroupLayout(jPanelGestionRedfox);
        jPanelGestionRedfox.setLayout(jPanelGestionRedfoxLayout);
        jPanelGestionRedfoxLayout.setHorizontalGroup(
            jPanelGestionRedfoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );
        jPanelGestionRedfoxLayout.setVerticalGroup(
            jPanelGestionRedfoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanelGestionRedfox);

        jPanelGestionNotifications.setBorder(javax.swing.BorderFactory.createTitledBorder("Notifications"));

        javax.swing.GroupLayout jPanelGestionNotificationsLayout = new javax.swing.GroupLayout(jPanelGestionNotifications);
        jPanelGestionNotifications.setLayout(jPanelGestionNotificationsLayout);
        jPanelGestionNotificationsLayout.setHorizontalGroup(
            jPanelGestionNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelGestionNotificationsLayout.setVerticalGroup(
            jPanelGestionNotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanelGestionNotifications);

        javax.swing.GroupLayout jPanelAideGestionUtilisateurLayout = new javax.swing.GroupLayout(jPanelAideGestionUtilisateur);
        jPanelAideGestionUtilisateur.setLayout(jPanelAideGestionUtilisateurLayout);
        jPanelAideGestionUtilisateurLayout.setHorizontalGroup(
            jPanelAideGestionUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelAideGestionUtilisateurLayout.setVerticalGroup(
            jPanelAideGestionUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", jPanelAideGestionUtilisateur);

        javax.swing.GroupLayout jPanelAideGestionJeuxLayout = new javax.swing.GroupLayout(jPanelAideGestionJeux);
        jPanelAideGestionJeux.setLayout(jPanelAideGestionJeuxLayout);
        jPanelAideGestionJeuxLayout.setHorizontalGroup(
            jPanelAideGestionJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelAideGestionJeuxLayout.setVerticalGroup(
            jPanelAideGestionJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab6", jPanelAideGestionJeux);

        javax.swing.GroupLayout jPanelAccueilAideLayout = new javax.swing.GroupLayout(jPanelAccueilAide);
        jPanelAccueilAide.setLayout(jPanelAccueilAideLayout);
        jPanelAccueilAideLayout.setHorizontalGroup(
            jPanelAccueilAideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        jPanelAccueilAideLayout.setVerticalGroup(
            jPanelAccueilAideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));

        jMenuAccueil.setText("Menu principal");
        jMenuAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAccueilRetourAccueil(evt);
            }
        });
        jMenuBar1.add(jMenuAccueil);

        jMenuGestionUnilan.setText("Gestion de Unilan");
        jMenuGestionUnilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGestionUnilanActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuGestionUnilan);

        jMenuGestionRedfox.setText("Gestion de Redfox");
        jMenuBar1.add(jMenuGestionRedfox);

        jMenuAlarmes.setText("Notifications");
        jMenuBar1.add(jMenuAlarmes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAccueilAide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelAccueilAide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAccueilRetourAccueil(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAccueilRetourAccueil

      

    }//GEN-LAST:event_jMenuAccueilRetourAccueil

    private void jMenuGestionUnilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGestionUnilanActionPerformed

    }//GEN-LAST:event_jMenuGestionUnilanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAideAdhésions;
    private javax.swing.JButton jButtonAideGestionAdmin;
    private javax.swing.JButton jButtonAideGestionJeux;
    private javax.swing.JButton jButtonAideGestionUtilisateur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenuAccueil;
    private javax.swing.JMenu jMenuAlarmes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGestionRedfox;
    private javax.swing.JMenu jMenuGestionUnilan;
    private javax.swing.JPanel jPanelAccueilAide;
    private javax.swing.JPanel jPanelAideGestionJeux;
    private javax.swing.JPanel jPanelAideGestionUtilisateur;
    private javax.swing.JPanel jPanelDescriptionAide;
    private javax.swing.JPanel jPanelGesionUnilan;
    private javax.swing.JPanel jPanelGestionNotifications;
    private javax.swing.JPanel jPanelGestionRedfox;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
